### ISSUE TITLE
Multiple stream with same title cause an internal server error

### ISSUE THREAD

**Issue by zabirauf** [janjiss/elixir-stream-phoenix#3]
Creating multiple streams with exactly the same title results in internal server error when visiting the entry. In stream it shows fine but when visiting the URL for the entry, it throw 500

**Comment by janjiss** [comment]
@zabirauf Thanks for pointing this out! In the meantime, can you delete the post that is causing the issue? 
If you are logged in, you can delete it like so:
http://prntscr.com/7w04va

**Comment by zabirauf** [comment]
@janjiss Cant't see that option as I added that entry without registering.

**Comment by janjiss** [comment]
@zabirauf Added the validaton for title uniquness and removed your first entry.

**Comment by zabirauf** [comment]
@janjiss Thanks :)
